// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: events/v1/promotion_events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromotionPublishedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromotionId  string   `protobuf:"bytes,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	Code         string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Percentage   int32    `protobuf:"varint,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	TargetGymIds []string `protobuf:"bytes,4,rep,name=target_gym_ids,json=targetGymIds,proto3" json:"target_gym_ids,omitempty"`
	StartDate    string   `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate      string   `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *PromotionPublishedEvent) Reset() {
	*x = PromotionPublishedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_v1_promotion_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromotionPublishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionPublishedEvent) ProtoMessage() {}

func (x *PromotionPublishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_promotion_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionPublishedEvent.ProtoReflect.Descriptor instead.
func (*PromotionPublishedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_promotion_events_proto_rawDescGZIP(), []int{0}
}

func (x *PromotionPublishedEvent) GetPromotionId() string {
	if x != nil {
		return x.PromotionId
	}
	return ""
}

func (x *PromotionPublishedEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PromotionPublishedEvent) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *PromotionPublishedEvent) GetTargetGymIds() []string {
	if x != nil {
		return x.TargetGymIds
	}
	return nil
}

func (x *PromotionPublishedEvent) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PromotionPublishedEvent) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

var File_events_v1_promotion_events_proto protoreflect.FileDescriptor

var file_events_v1_promotion_events_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xd0, 0x01,
	0x0a, 0x17, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x79, 0x6d, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x47, 0x79, 0x6d, 0x49, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x42, 0x4c, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x70, 0x6c, 0x6f, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_v1_promotion_events_proto_rawDescOnce sync.Once
	file_events_v1_promotion_events_proto_rawDescData = file_events_v1_promotion_events_proto_rawDesc
)

func file_events_v1_promotion_events_proto_rawDescGZIP() []byte {
	file_events_v1_promotion_events_proto_rawDescOnce.Do(func() {
		file_events_v1_promotion_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_promotion_events_proto_rawDescData)
	})
	return file_events_v1_promotion_events_proto_rawDescData
}

var file_events_v1_promotion_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_promotion_events_proto_goTypes = []interface{}{
	(*PromotionPublishedEvent)(nil), // 0: events.v1.PromotionPublishedEvent
}
var file_events_v1_promotion_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_promotion_events_proto_init() }
func file_events_v1_promotion_events_proto_init() {
	if File_events_v1_promotion_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_events_v1_promotion_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromotionPublishedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_promotion_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_promotion_events_proto_goTypes,
		DependencyIndexes: file_events_v1_promotion_events_proto_depIdxs,
		MessageInfos:      file_events_v1_promotion_events_proto_msgTypes,
	}.Build()
	File_events_v1_promotion_events_proto = out.File
	file_events_v1_promotion_events_proto_rawDesc = nil
	file_events_v1_promotion_events_proto_goTypes = nil
	file_events_v1_promotion_events_proto_depIdxs = nil
}
