// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: checkin/v1/checkin.proto

package checkinv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CheckInService_ProcessScan_FullMethodName             = "/checkin.v1.CheckInService/ProcessScan"
	CheckInService_GetMyCheckInHistory_FullMethodName     = "/checkin.v1.CheckInService/GetMyCheckInHistory"
	CheckInService_GetMemberCheckInHistory_FullMethodName = "/checkin.v1.CheckInService/GetMemberCheckInHistory"
	CheckInService_GetDailyCount_FullMethodName           = "/checkin.v1.CheckInService/GetDailyCount"
	CheckInService_GetDisplayQrPayload_FullMethodName     = "/checkin.v1.CheckInService/GetDisplayQrPayload"
	CheckInService_RotateGymQrRootKey_FullMethodName      = "/checkin.v1.CheckInService/RotateGymQrRootKey"
)

// CheckInServiceClient is the client API for CheckInService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckInServiceClient interface {
	ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanResponse, error)
	GetMyCheckInHistory(ctx context.Context, in *GetMyCheckInHistoryRequest, opts ...grpc.CallOption) (*GetMyCheckInHistoryResponse, error)
	GetMemberCheckInHistory(ctx context.Context, in *GetMemberCheckInHistoryRequest, opts ...grpc.CallOption) (*GetMemberCheckInHistoryResponse, error)
	GetDailyCount(ctx context.Context, in *GetDailyCountRequest, opts ...grpc.CallOption) (*GetDailyCountResponse, error)
	GetDisplayQrPayload(ctx context.Context, in *GetDisplayQrPayloadRequest, opts ...grpc.CallOption) (*GetDisplayQrPayloadResponse, error)
	RotateGymQrRootKey(ctx context.Context, in *RotateGymQrRootKeyRequest, opts ...grpc.CallOption) (*RotateGymQrRootKeyResponse, error)
}

type checkInServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckInServiceClient(cc grpc.ClientConnInterface) CheckInServiceClient {
	return &checkInServiceClient{cc}
}

func (c *checkInServiceClient) ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanResponse, error) {
	out := new(ProcessScanResponse)
	err := c.cc.Invoke(ctx, CheckInService_ProcessScan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) GetMyCheckInHistory(ctx context.Context, in *GetMyCheckInHistoryRequest, opts ...grpc.CallOption) (*GetMyCheckInHistoryResponse, error) {
	out := new(GetMyCheckInHistoryResponse)
	err := c.cc.Invoke(ctx, CheckInService_GetMyCheckInHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) GetMemberCheckInHistory(ctx context.Context, in *GetMemberCheckInHistoryRequest, opts ...grpc.CallOption) (*GetMemberCheckInHistoryResponse, error) {
	out := new(GetMemberCheckInHistoryResponse)
	err := c.cc.Invoke(ctx, CheckInService_GetMemberCheckInHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) GetDailyCount(ctx context.Context, in *GetDailyCountRequest, opts ...grpc.CallOption) (*GetDailyCountResponse, error) {
	out := new(GetDailyCountResponse)
	err := c.cc.Invoke(ctx, CheckInService_GetDailyCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) GetDisplayQrPayload(ctx context.Context, in *GetDisplayQrPayloadRequest, opts ...grpc.CallOption) (*GetDisplayQrPayloadResponse, error) {
	out := new(GetDisplayQrPayloadResponse)
	err := c.cc.Invoke(ctx, CheckInService_GetDisplayQrPayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) RotateGymQrRootKey(ctx context.Context, in *RotateGymQrRootKeyRequest, opts ...grpc.CallOption) (*RotateGymQrRootKeyResponse, error) {
	out := new(RotateGymQrRootKeyResponse)
	err := c.cc.Invoke(ctx, CheckInService_RotateGymQrRootKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckInServiceServer is the server API for CheckInService service.
// All implementations must embed UnimplementedCheckInServiceServer
// for forward compatibility
type CheckInServiceServer interface {
	ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanResponse, error)
	GetMyCheckInHistory(context.Context, *GetMyCheckInHistoryRequest) (*GetMyCheckInHistoryResponse, error)
	GetMemberCheckInHistory(context.Context, *GetMemberCheckInHistoryRequest) (*GetMemberCheckInHistoryResponse, error)
	GetDailyCount(context.Context, *GetDailyCountRequest) (*GetDailyCountResponse, error)
	GetDisplayQrPayload(context.Context, *GetDisplayQrPayloadRequest) (*GetDisplayQrPayloadResponse, error)
	RotateGymQrRootKey(context.Context, *RotateGymQrRootKeyRequest) (*RotateGymQrRootKeyResponse, error)
	mustEmbedUnimplementedCheckInServiceServer()
}

// UnimplementedCheckInServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckInServiceServer struct {
}

func (UnimplementedCheckInServiceServer) ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessScan not implemented")
}
func (UnimplementedCheckInServiceServer) GetMyCheckInHistory(context.Context, *GetMyCheckInHistoryRequest) (*GetMyCheckInHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyCheckInHistory not implemented")
}
func (UnimplementedCheckInServiceServer) GetMemberCheckInHistory(context.Context, *GetMemberCheckInHistoryRequest) (*GetMemberCheckInHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberCheckInHistory not implemented")
}
func (UnimplementedCheckInServiceServer) GetDailyCount(context.Context, *GetDailyCountRequest) (*GetDailyCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyCount not implemented")
}
func (UnimplementedCheckInServiceServer) GetDisplayQrPayload(context.Context, *GetDisplayQrPayloadRequest) (*GetDisplayQrPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDisplayQrPayload not implemented")
}
func (UnimplementedCheckInServiceServer) RotateGymQrRootKey(context.Context, *RotateGymQrRootKeyRequest) (*RotateGymQrRootKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateGymQrRootKey not implemented")
}
func (UnimplementedCheckInServiceServer) mustEmbedUnimplementedCheckInServiceServer() {}

// UnsafeCheckInServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckInServiceServer will
// result in compilation errors.
type UnsafeCheckInServiceServer interface {
	mustEmbedUnimplementedCheckInServiceServer()
}

func RegisterCheckInServiceServer(s grpc.ServiceRegistrar, srv CheckInServiceServer) {
	s.RegisterService(&CheckInService_ServiceDesc, srv)
}

func _CheckInService_ProcessScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).ProcessScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_ProcessScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).ProcessScan(ctx, req.(*ProcessScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_GetMyCheckInHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCheckInHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).GetMyCheckInHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_GetMyCheckInHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).GetMyCheckInHistory(ctx, req.(*GetMyCheckInHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_GetMemberCheckInHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberCheckInHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).GetMemberCheckInHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_GetMemberCheckInHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).GetMemberCheckInHistory(ctx, req.(*GetMemberCheckInHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_GetDailyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).GetDailyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_GetDailyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).GetDailyCount(ctx, req.(*GetDailyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_GetDisplayQrPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisplayQrPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).GetDisplayQrPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_GetDisplayQrPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).GetDisplayQrPayload(ctx, req.(*GetDisplayQrPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_RotateGymQrRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateGymQrRootKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).RotateGymQrRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInService_RotateGymQrRootKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).RotateGymQrRootKey(ctx, req.(*RotateGymQrRootKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckInService_ServiceDesc is the grpc.ServiceDesc for CheckInService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckInService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checkin.v1.CheckInService",
	HandlerType: (*CheckInServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessScan",
			Handler:    _CheckInService_ProcessScan_Handler,
		},
		{
			MethodName: "GetMyCheckInHistory",
			Handler:    _CheckInService_GetMyCheckInHistory_Handler,
		},
		{
			MethodName: "GetMemberCheckInHistory",
			Handler:    _CheckInService_GetMemberCheckInHistory_Handler,
		},
		{
			MethodName: "GetDailyCount",
			Handler:    _CheckInService_GetDailyCount_Handler,
		},
		{
			MethodName: "GetDisplayQrPayload",
			Handler:    _CheckInService_GetDisplayQrPayload_Handler,
		},
		{
			MethodName: "RotateGymQrRootKey",
			Handler:    _CheckInService_RotateGymQrRootKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkin/v1/checkin.proto",
}
