// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plans/v1/plans.proto

package plansv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlansService_CreateGymLocation_FullMethodName      = "/plans.v1.PlansService/CreateGymLocation"
	PlansService_UpdateGymLocation_FullMethodName      = "/plans.v1.PlansService/UpdateGymLocation"
	PlansService_GetGymLocation_FullMethodName         = "/plans.v1.PlansService/GetGymLocation"
	PlansService_ListGymLocations_FullMethodName       = "/plans.v1.PlansService/ListGymLocations"
	PlansService_CreateMembershipPlan_FullMethodName   = "/plans.v1.PlansService/CreateMembershipPlan"
	PlansService_UpdateMembershipPlan_FullMethodName   = "/plans.v1.PlansService/UpdateMembershipPlan"
	PlansService_GetMembershipPlan_FullMethodName      = "/plans.v1.PlansService/GetMembershipPlan"
	PlansService_ListMembershipPlans_FullMethodName    = "/plans.v1.PlansService/ListMembershipPlans"
	PlansService_GetActiveGym_FullMethodName           = "/plans.v1.PlansService/GetActiveGym"
	PlansService_ResolvePurchasablePlan_FullMethodName = "/plans.v1.PlansService/ResolvePurchasablePlan"
)

// PlansServiceClient is the client API for PlansService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlansServiceClient interface {
	CreateGymLocation(ctx context.Context, in *CreateGymLocationRequest, opts ...grpc.CallOption) (*CreateGymLocationResponse, error)
	UpdateGymLocation(ctx context.Context, in *UpdateGymLocationRequest, opts ...grpc.CallOption) (*UpdateGymLocationResponse, error)
	GetGymLocation(ctx context.Context, in *GetGymLocationRequest, opts ...grpc.CallOption) (*GetGymLocationResponse, error)
	ListGymLocations(ctx context.Context, in *ListGymLocationsRequest, opts ...grpc.CallOption) (*ListGymLocationsResponse, error)
	CreateMembershipPlan(ctx context.Context, in *CreateMembershipPlanRequest, opts ...grpc.CallOption) (*CreateMembershipPlanResponse, error)
	UpdateMembershipPlan(ctx context.Context, in *UpdateMembershipPlanRequest, opts ...grpc.CallOption) (*UpdateMembershipPlanResponse, error)
	GetMembershipPlan(ctx context.Context, in *GetMembershipPlanRequest, opts ...grpc.CallOption) (*GetMembershipPlanResponse, error)
	ListMembershipPlans(ctx context.Context, in *ListMembershipPlansRequest, opts ...grpc.CallOption) (*ListMembershipPlansResponse, error)
	// Internal only. Requires the verified ms-gym-identifier workload identity.
	// This RPC is intentionally absent from the external HTTP configuration.
	GetActiveGym(ctx context.Context, in *GetActiveGymRequest, opts ...grpc.CallOption) (*GetActiveGymResponse, error)
	// Internal only. Requires the verified ms-gym-member workload identity.
	// This RPC is intentionally absent from the external HTTP configuration.
	ResolvePurchasablePlan(ctx context.Context, in *ResolvePurchasablePlanRequest, opts ...grpc.CallOption) (*ResolvePurchasablePlanResponse, error)
}

type plansServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlansServiceClient(cc grpc.ClientConnInterface) PlansServiceClient {
	return &plansServiceClient{cc}
}

func (c *plansServiceClient) CreateGymLocation(ctx context.Context, in *CreateGymLocationRequest, opts ...grpc.CallOption) (*CreateGymLocationResponse, error) {
	out := new(CreateGymLocationResponse)
	err := c.cc.Invoke(ctx, PlansService_CreateGymLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdateGymLocation(ctx context.Context, in *UpdateGymLocationRequest, opts ...grpc.CallOption) (*UpdateGymLocationResponse, error) {
	out := new(UpdateGymLocationResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdateGymLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetGymLocation(ctx context.Context, in *GetGymLocationRequest, opts ...grpc.CallOption) (*GetGymLocationResponse, error) {
	out := new(GetGymLocationResponse)
	err := c.cc.Invoke(ctx, PlansService_GetGymLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) ListGymLocations(ctx context.Context, in *ListGymLocationsRequest, opts ...grpc.CallOption) (*ListGymLocationsResponse, error) {
	out := new(ListGymLocationsResponse)
	err := c.cc.Invoke(ctx, PlansService_ListGymLocations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) CreateMembershipPlan(ctx context.Context, in *CreateMembershipPlanRequest, opts ...grpc.CallOption) (*CreateMembershipPlanResponse, error) {
	out := new(CreateMembershipPlanResponse)
	err := c.cc.Invoke(ctx, PlansService_CreateMembershipPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) UpdateMembershipPlan(ctx context.Context, in *UpdateMembershipPlanRequest, opts ...grpc.CallOption) (*UpdateMembershipPlanResponse, error) {
	out := new(UpdateMembershipPlanResponse)
	err := c.cc.Invoke(ctx, PlansService_UpdateMembershipPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetMembershipPlan(ctx context.Context, in *GetMembershipPlanRequest, opts ...grpc.CallOption) (*GetMembershipPlanResponse, error) {
	out := new(GetMembershipPlanResponse)
	err := c.cc.Invoke(ctx, PlansService_GetMembershipPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) ListMembershipPlans(ctx context.Context, in *ListMembershipPlansRequest, opts ...grpc.CallOption) (*ListMembershipPlansResponse, error) {
	out := new(ListMembershipPlansResponse)
	err := c.cc.Invoke(ctx, PlansService_ListMembershipPlans_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) GetActiveGym(ctx context.Context, in *GetActiveGymRequest, opts ...grpc.CallOption) (*GetActiveGymResponse, error) {
	out := new(GetActiveGymResponse)
	err := c.cc.Invoke(ctx, PlansService_GetActiveGym_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plansServiceClient) ResolvePurchasablePlan(ctx context.Context, in *ResolvePurchasablePlanRequest, opts ...grpc.CallOption) (*ResolvePurchasablePlanResponse, error) {
	out := new(ResolvePurchasablePlanResponse)
	err := c.cc.Invoke(ctx, PlansService_ResolvePurchasablePlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlansServiceServer is the server API for PlansService service.
// All implementations must embed UnimplementedPlansServiceServer
// for forward compatibility
type PlansServiceServer interface {
	CreateGymLocation(context.Context, *CreateGymLocationRequest) (*CreateGymLocationResponse, error)
	UpdateGymLocation(context.Context, *UpdateGymLocationRequest) (*UpdateGymLocationResponse, error)
	GetGymLocation(context.Context, *GetGymLocationRequest) (*GetGymLocationResponse, error)
	ListGymLocations(context.Context, *ListGymLocationsRequest) (*ListGymLocationsResponse, error)
	CreateMembershipPlan(context.Context, *CreateMembershipPlanRequest) (*CreateMembershipPlanResponse, error)
	UpdateMembershipPlan(context.Context, *UpdateMembershipPlanRequest) (*UpdateMembershipPlanResponse, error)
	GetMembershipPlan(context.Context, *GetMembershipPlanRequest) (*GetMembershipPlanResponse, error)
	ListMembershipPlans(context.Context, *ListMembershipPlansRequest) (*ListMembershipPlansResponse, error)
	// Internal only. Requires the verified ms-gym-identifier workload identity.
	// This RPC is intentionally absent from the external HTTP configuration.
	GetActiveGym(context.Context, *GetActiveGymRequest) (*GetActiveGymResponse, error)
	// Internal only. Requires the verified ms-gym-member workload identity.
	// This RPC is intentionally absent from the external HTTP configuration.
	ResolvePurchasablePlan(context.Context, *ResolvePurchasablePlanRequest) (*ResolvePurchasablePlanResponse, error)
	mustEmbedUnimplementedPlansServiceServer()
}

// UnimplementedPlansServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlansServiceServer struct {
}

func (UnimplementedPlansServiceServer) CreateGymLocation(context.Context, *CreateGymLocationRequest) (*CreateGymLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGymLocation not implemented")
}
func (UnimplementedPlansServiceServer) UpdateGymLocation(context.Context, *UpdateGymLocationRequest) (*UpdateGymLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGymLocation not implemented")
}
func (UnimplementedPlansServiceServer) GetGymLocation(context.Context, *GetGymLocationRequest) (*GetGymLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGymLocation not implemented")
}
func (UnimplementedPlansServiceServer) ListGymLocations(context.Context, *ListGymLocationsRequest) (*ListGymLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGymLocations not implemented")
}
func (UnimplementedPlansServiceServer) CreateMembershipPlan(context.Context, *CreateMembershipPlanRequest) (*CreateMembershipPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembershipPlan not implemented")
}
func (UnimplementedPlansServiceServer) UpdateMembershipPlan(context.Context, *UpdateMembershipPlanRequest) (*UpdateMembershipPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembershipPlan not implemented")
}
func (UnimplementedPlansServiceServer) GetMembershipPlan(context.Context, *GetMembershipPlanRequest) (*GetMembershipPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipPlan not implemented")
}
func (UnimplementedPlansServiceServer) ListMembershipPlans(context.Context, *ListMembershipPlansRequest) (*ListMembershipPlansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembershipPlans not implemented")
}
func (UnimplementedPlansServiceServer) GetActiveGym(context.Context, *GetActiveGymRequest) (*GetActiveGymResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveGym not implemented")
}
func (UnimplementedPlansServiceServer) ResolvePurchasablePlan(context.Context, *ResolvePurchasablePlanRequest) (*ResolvePurchasablePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePurchasablePlan not implemented")
}
func (UnimplementedPlansServiceServer) mustEmbedUnimplementedPlansServiceServer() {}

// UnsafePlansServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlansServiceServer will
// result in compilation errors.
type UnsafePlansServiceServer interface {
	mustEmbedUnimplementedPlansServiceServer()
}

func RegisterPlansServiceServer(s grpc.ServiceRegistrar, srv PlansServiceServer) {
	s.RegisterService(&PlansService_ServiceDesc, srv)
}

func _PlansService_CreateGymLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGymLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).CreateGymLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_CreateGymLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).CreateGymLocation(ctx, req.(*CreateGymLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdateGymLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGymLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdateGymLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdateGymLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdateGymLocation(ctx, req.(*UpdateGymLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetGymLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGymLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetGymLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetGymLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetGymLocation(ctx, req.(*GetGymLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_ListGymLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGymLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).ListGymLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_ListGymLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).ListGymLocations(ctx, req.(*ListGymLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_CreateMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).CreateMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_CreateMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).CreateMembershipPlan(ctx, req.(*CreateMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_UpdateMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).UpdateMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_UpdateMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).UpdateMembershipPlan(ctx, req.(*UpdateMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetMembershipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetMembershipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetMembershipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetMembershipPlan(ctx, req.(*GetMembershipPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_ListMembershipPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).ListMembershipPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_ListMembershipPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).ListMembershipPlans(ctx, req.(*ListMembershipPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_GetActiveGym_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveGymRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).GetActiveGym(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_GetActiveGym_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).GetActiveGym(ctx, req.(*GetActiveGymRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlansService_ResolvePurchasablePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePurchasablePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServiceServer).ResolvePurchasablePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlansService_ResolvePurchasablePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServiceServer).ResolvePurchasablePlan(ctx, req.(*ResolvePurchasablePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlansService_ServiceDesc is the grpc.ServiceDesc for PlansService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlansService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plans.v1.PlansService",
	HandlerType: (*PlansServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGymLocation",
			Handler:    _PlansService_CreateGymLocation_Handler,
		},
		{
			MethodName: "UpdateGymLocation",
			Handler:    _PlansService_UpdateGymLocation_Handler,
		},
		{
			MethodName: "GetGymLocation",
			Handler:    _PlansService_GetGymLocation_Handler,
		},
		{
			MethodName: "ListGymLocations",
			Handler:    _PlansService_ListGymLocations_Handler,
		},
		{
			MethodName: "CreateMembershipPlan",
			Handler:    _PlansService_CreateMembershipPlan_Handler,
		},
		{
			MethodName: "UpdateMembershipPlan",
			Handler:    _PlansService_UpdateMembershipPlan_Handler,
		},
		{
			MethodName: "GetMembershipPlan",
			Handler:    _PlansService_GetMembershipPlan_Handler,
		},
		{
			MethodName: "ListMembershipPlans",
			Handler:    _PlansService_ListMembershipPlans_Handler,
		},
		{
			MethodName: "GetActiveGym",
			Handler:    _PlansService_GetActiveGym_Handler,
		},
		{
			MethodName: "ResolvePurchasablePlan",
			Handler:    _PlansService_ResolvePurchasablePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plans/v1/plans.proto",
}
