// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_GetDailyAttendance_FullMethodName    = "/analytics.v1.AnalyticsService/GetDailyAttendance"
	AnalyticsService_GetAttendanceTrend_FullMethodName    = "/analytics.v1.AnalyticsService/GetAttendanceTrend"
	AnalyticsService_GetMembershipStats_FullMethodName    = "/analytics.v1.AnalyticsService/GetMembershipStats"
	AnalyticsService_GetInactiveMembers_FullMethodName    = "/analytics.v1.AnalyticsService/GetInactiveMembers"
	AnalyticsService_GetRevenueReport_FullMethodName      = "/analytics.v1.AnalyticsService/GetRevenueReport"
	AnalyticsService_GetRevenueComparison_FullMethodName  = "/analytics.v1.AnalyticsService/GetRevenueComparison"
	AnalyticsService_GetTrainerUtilization_FullMethodName = "/analytics.v1.AnalyticsService/GetTrainerUtilization"
	AnalyticsService_GetDashboardSummary_FullMethodName   = "/analytics.v1.AnalyticsService/GetDashboardSummary"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetDailyAttendance(ctx context.Context, in *GetDailyAttendanceRequest, opts ...grpc.CallOption) (*GetDailyAttendanceResponse, error)
	GetAttendanceTrend(ctx context.Context, in *GetAttendanceTrendRequest, opts ...grpc.CallOption) (*GetAttendanceTrendResponse, error)
	GetMembershipStats(ctx context.Context, in *GetMembershipStatsRequest, opts ...grpc.CallOption) (*GetMembershipStatsResponse, error)
	GetInactiveMembers(ctx context.Context, in *GetInactiveMembersRequest, opts ...grpc.CallOption) (*GetInactiveMembersResponse, error)
	GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error)
	GetRevenueComparison(ctx context.Context, in *GetRevenueComparisonRequest, opts ...grpc.CallOption) (*GetRevenueComparisonResponse, error)
	GetTrainerUtilization(ctx context.Context, in *GetTrainerUtilizationRequest, opts ...grpc.CallOption) (*GetTrainerUtilizationResponse, error)
	GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*GetDashboardSummaryResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetDailyAttendance(ctx context.Context, in *GetDailyAttendanceRequest, opts ...grpc.CallOption) (*GetDailyAttendanceResponse, error) {
	out := new(GetDailyAttendanceResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDailyAttendance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAttendanceTrend(ctx context.Context, in *GetAttendanceTrendRequest, opts ...grpc.CallOption) (*GetAttendanceTrendResponse, error) {
	out := new(GetAttendanceTrendResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAttendanceTrend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMembershipStats(ctx context.Context, in *GetMembershipStatsRequest, opts ...grpc.CallOption) (*GetMembershipStatsResponse, error) {
	out := new(GetMembershipStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMembershipStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetInactiveMembers(ctx context.Context, in *GetInactiveMembersRequest, opts ...grpc.CallOption) (*GetInactiveMembersResponse, error) {
	out := new(GetInactiveMembersResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetInactiveMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error) {
	out := new(GetRevenueReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRevenueReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRevenueComparison(ctx context.Context, in *GetRevenueComparisonRequest, opts ...grpc.CallOption) (*GetRevenueComparisonResponse, error) {
	out := new(GetRevenueComparisonResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRevenueComparison_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTrainerUtilization(ctx context.Context, in *GetTrainerUtilizationRequest, opts ...grpc.CallOption) (*GetTrainerUtilizationResponse, error) {
	out := new(GetTrainerUtilizationResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTrainerUtilization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*GetDashboardSummaryResponse, error) {
	out := new(GetDashboardSummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDashboardSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	GetDailyAttendance(context.Context, *GetDailyAttendanceRequest) (*GetDailyAttendanceResponse, error)
	GetAttendanceTrend(context.Context, *GetAttendanceTrendRequest) (*GetAttendanceTrendResponse, error)
	GetMembershipStats(context.Context, *GetMembershipStatsRequest) (*GetMembershipStatsResponse, error)
	GetInactiveMembers(context.Context, *GetInactiveMembersRequest) (*GetInactiveMembersResponse, error)
	GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error)
	GetRevenueComparison(context.Context, *GetRevenueComparisonRequest) (*GetRevenueComparisonResponse, error)
	GetTrainerUtilization(context.Context, *GetTrainerUtilizationRequest) (*GetTrainerUtilizationResponse, error)
	GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*GetDashboardSummaryResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) GetDailyAttendance(context.Context, *GetDailyAttendanceRequest) (*GetDailyAttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyAttendance not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAttendanceTrend(context.Context, *GetAttendanceTrendRequest) (*GetAttendanceTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceTrend not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMembershipStats(context.Context, *GetMembershipStatsRequest) (*GetMembershipStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetInactiveMembers(context.Context, *GetInactiveMembersRequest) (*GetInactiveMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInactiveMembers not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevenueReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRevenueComparison(context.Context, *GetRevenueComparisonRequest) (*GetRevenueComparisonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevenueComparison not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTrainerUtilization(context.Context, *GetTrainerUtilizationRequest) (*GetTrainerUtilizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainerUtilization not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*GetDashboardSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetDailyAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDailyAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDailyAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDailyAttendance(ctx, req.(*GetDailyAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAttendanceTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAttendanceTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAttendanceTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAttendanceTrend(ctx, req.(*GetAttendanceTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMembershipStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMembershipStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMembershipStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMembershipStats(ctx, req.(*GetMembershipStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetInactiveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInactiveMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetInactiveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetInactiveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetInactiveMembers(ctx, req.(*GetInactiveMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRevenueReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRevenueReport(ctx, req.(*GetRevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRevenueComparison_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueComparisonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRevenueComparison(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRevenueComparison_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRevenueComparison(ctx, req.(*GetRevenueComparisonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTrainerUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainerUtilizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTrainerUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTrainerUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTrainerUtilization(ctx, req.(*GetTrainerUtilizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboardSummary(ctx, req.(*GetDashboardSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyAttendance",
			Handler:    _AnalyticsService_GetDailyAttendance_Handler,
		},
		{
			MethodName: "GetAttendanceTrend",
			Handler:    _AnalyticsService_GetAttendanceTrend_Handler,
		},
		{
			MethodName: "GetMembershipStats",
			Handler:    _AnalyticsService_GetMembershipStats_Handler,
		},
		{
			MethodName: "GetInactiveMembers",
			Handler:    _AnalyticsService_GetInactiveMembers_Handler,
		},
		{
			MethodName: "GetRevenueReport",
			Handler:    _AnalyticsService_GetRevenueReport_Handler,
		},
		{
			MethodName: "GetRevenueComparison",
			Handler:    _AnalyticsService_GetRevenueComparison_Handler,
		},
		{
			MethodName: "GetTrainerUtilization",
			Handler:    _AnalyticsService_GetTrainerUtilization_Handler,
		},
		{
			MethodName: "GetDashboardSummary",
			Handler:    _AnalyticsService_GetDashboardSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
